services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=school_management'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
