CREATE TABLE admin
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personal_number             VARCHAR(10)                             NOT NULL,
    name                        VARCHAR(50)                             NOT NULL,
    surname                     VARCHAR(50)                             NOT NULL,
    gender                      VARCHAR(7)                              NOT NULL,
    birth_date                  date                                    NOT NULL,
    address                     VARCHAR(100)                            NOT NULL,
    city                        VARCHAR(100)                            NOT NULL,
    country                     VARCHAR(100),
    postal_code                 VARCHAR(20),
    phone_number                VARCHAR(20),
    role                        VARCHAR(20)                             NOT NULL,
    notes                       TEXT,
    email                       VARCHAR(150)                            NOT NULL,
    password                    VARCHAR(255)                            NOT NULL,
    created_by                  VARCHAR(100),
    created_date                TIMESTAMP WITHOUT TIME ZONE,
    modified_by                 VARCHAR(100),
    modified_date               TIMESTAMP WITHOUT TIME ZONE,
    photo                       VARCHAR(255),
    admin_number                BIGINT,
    department                  VARCHAR(255),
    active                      BOOLEAN                                 NOT NULL,
    accept_terms_and_conditions BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

CREATE TABLE attendance
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT                                  NOT NULL,
    subject_id BIGINT                                  NOT NULL,
    date       date                                    NOT NULL,
    status     VARCHAR(10)                             NOT NULL,
    notes      VARCHAR(255),
    CONSTRAINT pk_attendance PRIMARY KEY (id)
);

CREATE TABLE grades
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grade         VARCHAR(255),
    academic_year VARCHAR(255),
    semester      VARCHAR(255),
    date_given    date,
    student_id    BIGINT,
    teacher_id    BIGINT,
    subject_id    BIGINT,
    CONSTRAINT pk_grades PRIMARY KEY (id)
);

CREATE TABLE students
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personal_number         VARCHAR(10)                             NOT NULL,
    name                    VARCHAR(50)                             NOT NULL,
    surname                 VARCHAR(50)                             NOT NULL,
    gender                  VARCHAR(7)                              NOT NULL,
    birth_date              date                                    NOT NULL,
    address                 VARCHAR(100)                            NOT NULL,
    city                    VARCHAR(100)                            NOT NULL,
    country                 VARCHAR(100),
    postal_code             VARCHAR(20),
    phone_number            VARCHAR(20),
    role                    VARCHAR(20)                             NOT NULL,
    notes                   TEXT,
    email                   VARCHAR(150)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    created_by              VARCHAR(100),
    created_date            TIMESTAMP WITHOUT TIME ZONE,
    modified_by             VARCHAR(100),
    modified_date           TIMESTAMP WITHOUT TIME ZONE,
    photo                   VARCHAR(255),
    student_id              BIGINT,
    registered_date         date,
    grade                   VARCHAR(255),
    academic_year           VARCHAR(255),
    current_semester        VARCHAR(20),
    gpa                     DOUBLE PRECISION,
    completed_semesters     INTEGER,
    graduated               BOOLEAN,
    active                  BOOLEAN,
    guardian_name           VARCHAR(100),
    guardian_phone_number   VARCHAR(20),
    guardian_email          VARCHAR(100),
    relationship_to_student VARCHAR(255),
    emergency_contact_phone VARCHAR(20),
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE subjects
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

CREATE TABLE teacher_subject
(
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL
);

CREATE TABLE teachers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personal_number     VARCHAR(10)                             NOT NULL,
    name                VARCHAR(50)                             NOT NULL,
    surname             VARCHAR(50)                             NOT NULL,
    gender              VARCHAR(7)                              NOT NULL,
    birth_date          date                                    NOT NULL,
    address             VARCHAR(100)                            NOT NULL,
    city                VARCHAR(100)                            NOT NULL,
    country             VARCHAR(100),
    postal_code         VARCHAR(20),
    phone_number        VARCHAR(20),
    role                VARCHAR(20)                             NOT NULL,
    notes               TEXT,
    email               VARCHAR(150)                            NOT NULL,
    password            VARCHAR(255)                            NOT NULL,
    created_by          VARCHAR(100),
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    modified_by         VARCHAR(100),
    modified_date       TIMESTAMP WITHOUT TIME ZONE,
    photo               VARCHAR(255),
    teacher_id          BIGINT                                  NOT NULL,
    specialization      VARCHAR(100)                            NOT NULL,
    years_of_experience INTEGER                                 NOT NULL,
    salary              DOUBLE PRECISION,
    employment_date     date                                    NOT NULL,
    qualification       SMALLINT,
    CONSTRAINT pk_teachers PRIMARY KEY (id)
);

ALTER TABLE admin
    ADD CONSTRAINT uc_admin_email UNIQUE (email);

ALTER TABLE admin
    ADD CONSTRAINT uc_admin_personal_number UNIQUE (personal_number);

ALTER TABLE students
    ADD CONSTRAINT uc_students_email UNIQUE (email);

ALTER TABLE students
    ADD CONSTRAINT uc_students_personal_number UNIQUE (personal_number);

ALTER TABLE students
    ADD CONSTRAINT uc_students_student UNIQUE (student_id);

ALTER TABLE subjects
    ADD CONSTRAINT uc_subjects_name UNIQUE (name);

ALTER TABLE teachers
    ADD CONSTRAINT uc_teachers_email UNIQUE (email);

ALTER TABLE teachers
    ADD CONSTRAINT uc_teachers_personal_number UNIQUE (personal_number);

ALTER TABLE teachers
    ADD CONSTRAINT uc_teachers_teacher UNIQUE (teacher_id);

ALTER TABLE attendance
    ADD CONSTRAINT FK_ATTENDANCE_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE attendance
    ADD CONSTRAINT FK_ATTENDANCE_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teachers (id);

ALTER TABLE teacher_subject
    ADD CONSTRAINT fk_teasub_on_subject_entity FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE teacher_subject
    ADD CONSTRAINT fk_teasub_on_teacher_entity FOREIGN KEY (teacher_id) REFERENCES teachers (id);

