CREATE TABLE schedules
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_number INTEGER                                 NOT NULL,
    subject_id   BIGINT                                  NOT NULL,
    teacher_id   BIGINT                                  NOT NULL,
    day_of_week  INTEGER                                 NOT NULL,
    start_time   time WITHOUT TIME ZONE                  NOT NULL,
    end_time     time WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_schedules PRIMARY KEY (id)
);

ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teachers (id);